import React from 'react';
import { Modal } from './Modal';

interface TermsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function TermsModal({ isOpen, onClose }: TermsModalProps) {
  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Terms of Service"
      subtitle="Please read these terms carefully"
      aria-label="Terms of Service"
    >
      <div className="modal-prose">
        <p className="modal-effective-date">Effective date: January 1, 2026</p>

        <section className="modal-section">
          <h3>1. Use of Service</h3>
          <p>
            VibeSpin is provided as-is for personal and commercial use at no charge.
            You may use the app freely to randomize choices, run games, or support
            any lawful activity.
          </p>
        </section>

        <section className="modal-section">
          <h3>2. No Warranties</h3>
          <p>
            The service is provided without warranties or guarantees of any kind,
            express or implied. We make no representations regarding the availability,
            accuracy, or reliability of wheel outcomes.
          </p>
        </section>

        <section className="modal-section">
          <h3>3. Limitation of Liability</h3>
          <p>
            VibeSpin is not responsible for any decisions made based on wheel
            outcomes. Users accept full responsibility for how they act on the
            results generated by the app.
          </p>
        </section>

        <section className="modal-section">
          <h3>4. Prohibited Uses</h3>
          <p>
            You may not use VibeSpin for any unlawful purpose, to harass others,
            to distribute malicious content, or in any manner that violates
            applicable local, national, or international law or regulation.
          </p>
        </section>

        <section className="modal-section">
          <h3>5. Changes to These Terms</h3>
          <p>
            We may update these Terms at any time. Continued use of VibeSpin after
            changes are posted constitutes your acceptance of the revised Terms.
            We encourage you to review this page periodically.
          </p>
        </section>

        <p className="modal-contact">
          Questions?{' '}
          <a href="mailto:hello@tawdball.tech">hello@tawdball.tech</a>
        </p>
      </div>
    </Modal>
  );
}
